version: '3.4'

services:
  trulyapi:
    image: ${DOCKER_REGISTRY-}trulyapi
    build:
      context: .
      dockerfile: TrulyApi/Dockerfile
    environment:      
      - "ConnectionStrings__DefaultConnection=Server=db;Database=TrulyApiDb;User=sa;Password=Your_password123;MultipleActiveResultSets=true;Encrypt=False"      
      - "IdentityServer__Key__Type=Development"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=Your_password123"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
    depends_on:
      - "db"

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=Your_password123"
      - "ACCEPT_EULA=Y"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets